tools:
  ClangFormat:
    include:
      match: &cpp_patterns
      - .*src/steps/.*\.((h)|(cpp)|(hpp))$
      - .*test/unit/.*\.((h)|(cpp)|(hpp))$
  CMakeFormat:
    enable: True
  ClangTidy:
    option: --fix
    include:
      match:
      - .*src/steps/.*\.cpp$
