#!/bin/sh
export LIBTOOLIZE=/usr/local/bin/libtoolize
export AUTOCONF=/usr/local/bin/autoconf
#"$LIBTOOLIZE" --ltdl --copy --force
"$LIBTOOLIZE" --copy --force

# Gather macros required for autoconf.
aclocal -I config

#
autoheader

# 
automake --foreign --add-missing --copy

#
$AUTOCONF