# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _wmdirect_core
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


create = _wmdirect_core.create
destroy = _wmdirect_core.destroy
set_rng = _wmdirect_core.set_rng
species_create = _wmdirect_core.species_create
comp_create = _wmdirect_core.comp_create
comp_species_add = _wmdirect_core.comp_species_add
setup = _wmdirect_core.setup
reset = _wmdirect_core.reset
step = _wmdirect_core.step
run = _wmdirect_core.run
get_time = _wmdirect_core.get_time
get_nsteps = _wmdirect_core.get_nsteps
get_comp_vol = _wmdirect_core.get_comp_vol
set_comp_vol = _wmdirect_core.set_comp_vol
get_comp_count = _wmdirect_core.get_comp_count
set_comp_count = _wmdirect_core.set_comp_count
get_comp_mass = _wmdirect_core.get_comp_mass
set_comp_mass = _wmdirect_core.set_comp_mass
get_comp_conc = _wmdirect_core.get_comp_conc
set_comp_conc = _wmdirect_core.set_comp_conc
get_comp_buffer = _wmdirect_core.get_comp_buffer
set_comp_buffer = _wmdirect_core.set_comp_buffer


