# -*- coding: utf-8 -*-
# cython:language_level=3str
###___license_placeholder___###

# =====================================================================================================================
# These bindings were automatically generated by cyWrap. Please do dot modify.
# Additional functionality shall be implemented in sub-classes.
#
__copyright__ = "Copyright 2016 EPFL BBP-project"
# =====================================================================================================================

from cython.operator cimport dereference as deref
#from libcpp.memory cimport unique_ptr, shared_ptr
cimport std
from libcpp cimport bool
from libc.stdio cimport printf, sprintf #debug

include "cysteps__globals.pyx"


# ======================================================================================================================
# Bindings to main namespace
# ======================================================================================================================
from steps cimport *

#Static funcs
def _py_init():
    init()

def _py_finish():
    finish()

def _py_permeability(G, V, z, T, iconc, oconc):
    return permeability(G, V, z, T, iconc, oconc)

_USE_PETSC = USE_PETSC
_STEPS_USE_DIST_MESH = STEPS_USE_DIST_MESH

# ======================================================================================================================
# Bindings to module namespace
# ======================================================================================================================
include "cysteps_model.pyx"
include "cysteps_geom.pyx"
include "cysteps_solver.pyx"
include "cysteps_rng.pyx"
